# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_panels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelinfo',
            old_name='coord_x',
            new_name='coordinate_x',
        ),
        migrations.RenameField(
            model_name='panelinfo',
            old_name='coord_y',
            new_name='coordinate_y',
        ),
    ]
