# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('cms_panels', '0003_auto_20170704_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPanel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_panels_multipanel', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, default='', max_length=200, verbose_name='CSS class')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='In navigation')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('height', models.CharField(blank=True, default='', max_length=100, verbose_name='Height')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='Width')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=150, verbose_name='Slug')),
                ('cms_page', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_panels_multipanel_set', to='cms.Page')),
            ],
            options={
                'verbose_name': 'Panel ',
                'verbose_name_plural': 'Panels',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='panel',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_panels_panel_set', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='filer_image',
            field=filer.fields.image.FilerImageField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_panels_panel_image_set', to='filer.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='panelinfo',
            name='coordinate_x',
            field=models.PositiveIntegerField(blank=True, default='5000', verbose_name='X coordinat'),
        ),
        migrations.AlterField(
            model_name='panelinfo',
            name='coordinate_y',
            field=models.PositiveIntegerField(blank=True, default='5000', verbose_name='Y coordinat'),
        ),
    ]
