# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cms_panels', '0004_auto_20170710_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'verbose_name': 'Panel', 'verbose_name_plural': 'Panels'},
        ),
        migrations.AlterModelOptions(
            name='panelinfo',
            options={'verbose_name': 'Panel Info', 'verbose_name_plural': 'Panel Infos'},
        ),
        migrations.AddField(
            model_name='panelinfo',
            name='menu_filer_icon',
            field=filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_panels_panelinfo_menu_filer_icon_set', to='filer.File', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='panelinfo',
            name='menu_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='panelinfo',
            name='filer_icon',
            field=filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_panels_panelinfo_filer_icon_set', to='filer.File', verbose_name='Icon'),
        ),
    ]
