# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_panels', '0005_auto_20170717_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelinfo',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Name'),
        ),
    ]
