# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cms_panels', '0006_auto_20170717_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelinfo',
            name='menu_filer_icon',
        ),
        migrations.RemoveField(
            model_name='panelinfo',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='panel',
            name='menu_filer_icon',
            field=filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_panels_panelinfo_menu_filer_icon_set', to='filer.File', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='panel',
            name='menu_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Name'),
        ),
    ]
