# Generated by Django 2.2.9 on 2020-01-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_panels', '0007_auto_20170717_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipanel',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_panels_multipanel_set', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_panels_panel_set', to='cms.Page'),
        ),
    ]
